Add finalfusion tensorflow op.
finalfusion/finalfusion-tensorflow pull request #1
Opened 2019-09-06 06:16 UTC by sebpuetz

This PR is still missing documentation and some polishing, but it builds and can be loaded with both pip installed and compiled tensorflow 1.14 and 2.0.

Also, some python unit tests are missing.

2019-09-06 11:28 UTC, sebpuetz commented on finalfusion-tf/kernel/ff_lookup_kernels.cc
> +          return CreateFFLookup(path, mmap, lookup);
I tried to get rid of the static `CreateFFLookup` method, but if I'm reading `LookupOrCreateResource` correctly, it expects a function that returns `Status`, which rules out using the `FFLookup` constructor here and also requires us to pass a reference into the method and initialize it in the method.

```C++
template <typename T>
Status LookupOrCreateResource(OpKernelContext* ctx, const ResourceHandle& p,
                              T** value, std::function<Status(T**)> creator);
```

2019-09-06 11:30 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -DNDEBUG")
`-DNDEBUG` is required per https://github.com/tensorflow/tensorflow/issues/17316, otherwise there are failed assertions when exiting

2019-09-10 12:29 UTC, sebpuetz commented
@danieldk would you prefer a smaller PR only adding the `FFLookup` Resource? Although it would remove some context such as: https://github.com/finalfusion/finalfusion-tensorflow/pull/1#discussion_r321692168

2019-09-11 22:39 UTC, sebpuetz commented on include/finalfusion-tf/FFLookup.hh
> +Status CreateFFLookup(string const &path, bool mmap, FFLookup **result);
Reasoning for this `Status` method is given here: https://github.com/finalfusion/finalfusion-tensorflow/pull/1#discussion_r321692168

2019-09-12 09:39 UTC, danieldk requested changes
Some small comments.

2019-09-12 09:39 UTC, danieldk commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
Get the dynamic library extension using CMake. `.so` is `.dylib` on macOS. Also, can you get the SO version of the `TF_CFG`? Or perhaps the whole library name?

2019-09-12 09:39 UTC, danieldk commented on include/finalfusion-tf/FFLookup.hh
> +using namespace tensorflow;
Not in headers.

2019-09-12 09:39 UTC, danieldk commented on finalfusion-tf/lookup/FFLookup.cc
> +FFLookup::FFLookup(string const &path, bool mmap)
How does the `std` namespace get in here? Does Tensorflow import the namespace in a public header?

2019-09-12 09:39 UTC, danieldk commented on finalfusion-tf/lookup/FFLookup.cc
> +Status CreateFFLookup(const string &path, const bool mmap, FFLookup **result) {
`string const`

2019-09-12 09:39 UTC, danieldk commented on include/finalfusion-tf/FFLookup.hh
> +  std::unique_ptr <Embeddings> embeddings_;
Does this need to be a pointer member?

2019-09-12 09:39 UTC, danieldk commented on include/finalfusion-tf/FFLookup.hh
> +
Do you need a virtual destructor?

2019-09-12 09:39 UTC, danieldk commented on include/finalfusion-tf/FFLookup.hh
> +  std::vector<float> embedding(const string &word);
`string const`

2019-09-12 09:51 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
We also assumed `.so` and `.a` file endings in `finalfusion-ffi`, we might want to revisit that as well to build on other OSs?

> Also, can you get the SO version of the TF_CFG? Or perhaps the whole library name?

I can get the linker and compiler flags from tensorflow through: 
```
tf.sysconfig.get_link_flags()
> ['-L/home/seb/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow', 
 '-l:libtensorflow_framework.so.1']

tf.sysconfig.get_compile_flags()
> ['-I/home/seb/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/include',
 '-D_GLIBCXX_USE_CXX11_ABI=1']
```

We'd get the correct file ending and version of the shared library if we set the linker flags instead of setting up `libtensorflow_framework` as an imported library.

Other workaround would be prying out the right version and filename in a python script.

What do you think is preferable?

2019-09-12 10:05 UTC, sebpuetz commented on include/finalfusion-tf/FFLookup.hh
> +  std::unique_ptr <Embeddings> embeddings_;
Probably not

2019-09-12 10:06 UTC, sebpuetz commented on finalfusion-tf/lookup/FFLookup.cc
> +FFLookup::FFLookup(string const &path, bool mmap)
Looks like it, I didn't dig through enough tensorflow headers to find where that's coming from but strings are just `string` and not `std::string` in there.

2019-09-12 10:25 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
I think this is also a valid way:
```
find_library(LIBTENSORFLOW_FRAMEWORK NAMES libtensorflow_framework* PATHS ${LIBTENSORFLOW_FRAMEWORK_PATH})
```

2019-09-12 11:24 UTC, danieldk commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
> We also assumed `.so` and `.a` file endings in `finalfusion-ffi`, we might want to revisit that as well to build on other OSs?

`.a` is also the default on macOS, but we should definitely revisit the `.so` default.

> I can get the linker and compiler flags from tensorflow through:

It's a shame that we cannot use pkgconfig directly (for which CMake has a module). I assume that the Python package does not include `.pc` files right?

> We'd get the correct file ending and version of the shared library if we set the linker flags instead of setting up `libtensorflow_framework` as an imported library.

Fair enough. I'd do that. We do not need automatic rebuilds of libtensorflow_framework changes anyway, since it's not supposed to change.

2019-09-12 11:32 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
> It's a shame that we cannot use pkgconfig directly (for which CMake has a module). I assume that the Python package does not include .pc files right?

I didn't find anything `.pc` in the tensorflow package.

I did some digging in the Python package:

```
@tf_export('sysconfig.get_link_flags')
def get_link_flags():
  """Get the link flags for custom operators.

  Returns:
    The link flags.
  """
  is_mac = _platform.system() == 'Darwin'
  ver = _VERSION.split('.')[0]
  flags = []
  if not _MONOLITHIC_BUILD:
    flags.append('-L%s' % get_lib())
    if is_mac:
      flags.append('-l:libtensorflow_framework.%s.dylib' % ver)
    else:
      flags.append('-l:libtensorflow_framework.so.%s' % ver)
  return flags
```

is how the linker flags are generated. All the values are exposed through the public API, so we could just follow that to get the right path.

2019-09-12 12:58 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
I've added a build for OSX to CI which would verify that we find the correct file

2019-09-12 13:12 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
OSX build is broken because the tests of the submodules include the hard-coded `.so` file ending. I'll revert this for now. We could either put this PR on ice until we have updated `finalfusion-ffi` and `finalfusion-cxx` or add the OSX build later on, what do you think?

2019-09-12 17:00 UTC, sebpuetz commented
If the OSX build goes through, we should be good to go on this one?

2019-09-12 17:01 UTC, danieldk commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
I noticed that you added something along these lines, but can't you directly use this function? Then it'll work if they ever change the logic or library naming...

2019-09-12 17:14 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
I had an earlier iteration that took the output of `get_link_flags` and `get_compile_flags`. I'll have to dig that up again. Then we'd drop the `libtensorflow_framework` target and would give the linker flags to explicitly to the `finalfusion_tf` target?

2019-09-12 17:44 UTC, danieldk approved these changes

2019-09-12 17:47 UTC, sebpuetz commented
I'm trying to get this to work with the full implementation, but so far some symbols get lost along the way. When I try to load the shared library, some symbols from `libtensorflow_framework` are undefined. So I guess something's not working properly here?
```
NotFoundError: ./finalfusion-tf/libfinalfusion_tf_op.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

```
$ nm -g /home/seb/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/libtensorflow_framework.so.1 | grep "8OpKernelE"
[...]
0000000001c81030 V _ZTIN10tensorflow8OpKernelE
0000000001722c10 V _ZTSN10tensorflow8OpKernelE
0000000001c810c0 V _ZTVN10tensorflow8OpKernelE
```

```
$ ldd finalfusion-tf/libfinalfusion_tf_op.so
	linux-vdso.so.1 (0x00007fff3b834000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9c791c9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9c78faa000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9c78c21000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9c78883000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9c7866b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9c7827a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9c79755000)
```

2019-09-12 18:01 UTC, sebpuetz commented on finalfusion-tf/CMakeLists.txt
> +set(LIBTENSORFLOW_FRAMEWORK "${LIBTENSORFLOW_FRAMEWORK}/libtensorflow_framework.so.1")
Apparently I had to add the flags just like I'd pass a library to link instead of using `set_target_properties`:
```
target_link_libraries(finalfusion_tf finalfusion_cxx ${TF_LINK_FLAGS})
```

2019-09-12 18:10 UTC, merged